### ISSUE TITLE
数据为空

### ISSUE THREAD

**Issue by Zhoushujuan829** [yzhuo33/BandGapPredictor#1]
您好，我在运行的时候它一直报数据为空（ValueError: Input contains NaN, infinity or a value too large for dtype('float64').），我输出发现X（X = pd.DataFrame(features, columns=gf.column_names)）的值是空的，在class Vectorize_Formula类里面，def get_features(self, formula):这个函数没有进去直接抛出异常了

**Comment by yzhuo33** [comment]
> 您好，我在运行的时候它一直报数据为空（ValueError: Input contains NaN, infinity or a value too large for dtype('float64').），我输出发现X（X = pd.DataFrame(features, columns=gf.column_names)）的值是空的，在class Vectorize_Formula类里面，def get_features(self, formula):这个函数没有进去直接抛出异常了

Hello Shujuan! I would advise you to check the compounds in your "to_predict.xlsx" file. The composed elements must be included in "elements.xlsx". Also, you cannot have sodium nitride (NaN) in "to_predict.xlsx" as it could also generate this type of errors.

**Comment by alexey-krasnov** [comment]
Dear @yzhuo33! I got the same error. I just tried to use your code with your xlsx files and got the message:

There was an error with the Formula: BaCO3, this is a general exception with an unkown error
There was an error with the Formula: AgCl, this is a general exception with an unkown error
There was an error with the Formula: Zr2Co, this is a general exception with an unkown error
There was an error with the Formula: TiCo3, this is a general exception with an unkown error
There was an error with the Formula: LiFeP, this is a general exception with an unkown error
There was an error with the Formula: YAlO3, this is a general exception with an unkown error
/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/base.py:438: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(
Traceback (most recent call last):
  File "/Users/alexey-krasnov/Desktop/works/working_pythons/BandGapPredictor/Eg_model.py", line 99, in <module>
    result_c = pred_c.predict(X_c)
  File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/base.py", line 561, in _validate_data
    X = check_array(X, **check_params)
  File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/utils/validation.py", line 792, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Process finished with exit code 1

Please, explore what is wrong with the code or files?

**Comment by yzhuo33** [comment]
> Dear @yzhuo33! I got the same error. I just tried to use your code with your xlsx files and got the message:
> 
> There was an error with the Formula: BaCO3, this is a general exception with an unkown error There was an error with the Formula: AgCl, this is a general exception with an unkown error There was an error with the Formula: Zr2Co, this is a general exception with an unkown error There was an error with the Formula: TiCo3, this is a general exception with an unkown error There was an error with the Formula: LiFeP, this is a general exception with an unkown error There was an error with the Formula: YAlO3, this is a general exception with an unkown error /Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/base.py:438: UserWarning: X has feature names, but StandardScaler was fitted without feature names warnings.warn( Traceback (most recent call last): File "/Users/alexey-krasnov/Desktop/works/working_pythons/BandGapPredictor/Eg_model.py", line 99, in result_c = pred_c.predict(X_c) File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict y = super().predict(X) File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict X = self._validate_for_predict(X) File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict X = self._validate_data( File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/base.py", line 561, in _validate_data X = check_array(X, **check_params) File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/utils/validation.py", line 792, in check_array _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan") File "/Users/alexey-krasnov/miniforge3/envs/works/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite raise ValueError( ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
> 
> Process finished with exit code 1
> 
> Please, explore what is wrong with the code or files?

Hi Alexey! I updated the Eg_model.py. The issue was caused by the library updates or operating system incompatibility. Hope the new script works for you!

**Comment by alexey-krasnov** [comment]
Dear @yzhuo33! Thank you for this update. The code is working now fine, and it is fascinating. I checked my experimental compounds and found excellent accuracy with predicted values - the discrepancy is in the range of 1 -9 %. 

However, for some wide-gap semiconductors, the code gives Eg=0 eV. This is quite strange because 0 eV was obtained for TiO2, NaCl, which actually are in the training set. I also tried pyrochlore Bi2Ti2O7 and got 0 eV, however, we estimated its band gap as 3.19 eV. Could you please explain this confusion?

**Comment by ankit3388** [comment]
Hi This code can pridict band gap of topological insulator ???

**Comment by alexey-krasnov** [comment]
Hi @ankit3388 I suppose the model doesn't matter about crystal structure and can only use the provided chemical formula. You can try it out for your chemical composition and compare the prediction with experimental data (if available). Please check this [branch](https://github.com/alexey-krasnov/BandGapPredictor/tree/master) in which the model was updated for a better one to get better accuracy.
